### ISSUE TITLE
Implementation may be wrong

### ISSUE THREAD

**Issue by YouCaiJun98** [SaoYan/DnCNN-PyTorch#11]
Hello and thanks for your reproduction!
When I went through model.py, I noticed that in the forward method, you returned `out` instead of `x - out`, which is corresponding to residual learning in the author's article, I wonder if it's a mistake or I missed something. Thanks!

**Comment by visibh** [comment]
@YouCaiJun98 I still see the issue with the code or, you were able to spot it somewhere in the code?

**Comment by YouCaiJun98** [comment]
It turns out that the authors reproduce the model to predict AGWN instead of the whole image (see issue#4). 
You can safely employ the model to reconstruct the whole image with minor adjustments as stated above.

**Comment by visibh** [comment]
Yes, you are right. He is predicting the residual. I found it after you pointed to the source. Thank you.
For reference (for other readers), the line implementing residual noise concept is [here](https://github.com/SaoYan/DnCNN-PyTorch/blob/6b0804951484eadb7f1ea24e8e5c9ede9bea485b/train.py#L80).
