### ISSUE TITLE
FFDNet in PyTorch

### ISSUE THREAD

**Issue by TouqeerAhmad** [SaoYan/DnCNN-PyTorch#2]
Hi SaoYan, 

I was wondering if by any chance you are working or already have PyTorch version of FFDNet. It is an advanced version of DnCNN -- but only MatConvNet version is available from author's GitHub.

https://github.com/cszn/FFDNet

Thanks,
Touqeer

**Comment by SaoYan** [comment]
Hello Touqeer,

I'm afraid I don't have time to implement it recently, but I'd be glad to do it after finishing my recent work.

**Comment by fantasyzl** [comment]
Hi SaoYan
Thank you very much for open source related code. I have a little problem when I run the program. When I run train.py, there will always be "compare_psnr() got an unexpected keyword argument ‘data_range’”.

Thanks

**Comment by RoyiAvital** [comment]
> I'm afraid I don't have time to implement it recently, but I'd be glad to do it after finishing my recent work.

That would be amazing.
Especially if we can improve it and make it Correlated Noise aware.
