### ISSUE TITLE
AttributeError: 'Variable' object has no attribute 'item'

### ISSUE THREAD

**Issue by reborm** [SaoYan/DnCNN-PyTorch#3]
Hi, thank you for your share. When I train DnCNN-S, I get this error after I get the train.h5 and the val.h5.
Could you please help me solve it?
......
file: data/Set12/09.png
file: data/Set12/10.png
file: data/Set12/11.png
file: data/Set12/12.png
training set, # samples 238400

val set, # samples 12

Loading dataset ...

# of training samples: 238400

learning rate 0.001000
Traceback (most recent call last):
  File "train.py", line 126, in <module>
    main()
  File "train.py", line 88, in main
    (epoch+1, i+1, len(loader_train), loss.item(), psnr_train))
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/variable.py", line 67, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Variable' object has no attribute 'item'

**Comment by July250229** [comment]
How can you solve this?

**Comment by ZahiLam** [comment]
How can you solve this?
