### ISSUE TITLE
color images

### ISSUE THREAD

**Issue by kavita19** [SaoYan/DnCNN-PyTorch#8]
What changes required for color images?

**Comment by doboncho** [comment]
I change 
net = DnCNN(channels=3, num_of_layers=opt.num_of_layers)
in train.py.

But, below RuntimeErrot occured. Why?
RuntimeError: Given groups=1, weight of size [64, 3, 3, 3], expected input[128, 1, 40, 40] to have 3 channels, but got 1 channels instead

train and valid images are color images, off course.
